export class AppAssetObj{
    AppAssetId: any;
    AppId: any;
    AgrmntId: any;
    AssetSeqNo: any;
    FullAssetCode: any;
    FullAssetName: any;
    MrAssetConditionCode: any;
    MrAssetUsageCode: any;
    AssetStat: any;
    SerialNo1: any;
    SerialNo2: any;
    SerialNo3: any;
    SerialNo4: any;
    SerialNo5: any;
    AssetPriceAmt: any;
    DownPaymentAmt: any;
    AssetTypeCode: any;
    AssetCategoryCode: any;
    AssetTaxDt: any
    SupplCode: any;
    SupplName: any;
    IsCollateral: any;
    IsInsurance: any;
    AssetNotes: any;
    TempRegisLettNo: any;
    TempRegisLettDt: any;
    Color: any;
    TaxCityIssuer: any;
    TaxIssueDt: any;
    ManufacturingYear: any;
    IsEditableDp: any;
    RsvField1: any;
    RsvField2: any;
    RsvField3: any;
    RsvField4: any;
    RsvField5: any;
    RowVersion: any;
    constructor() { }
}