export class AppCustCompanyFinDataObj {
    AppCustCompanyFinDataId: any;
    AppCustId: any;
    GrossMonthlyIncomeAmt: any;
    GrossProfitAmt: any;
    GrossMonthlyExpenseAmt: any;
    ReturnOfInvestmentPrcnt: any;
    ReturnOfEquityPrcnt: any;
    ReturnOfAssetPrcnt: any;
    ProfitMarginPrcnt: any;
    CurrentRatioPrcnt: any;
    DebtEquityRatioPrcnt: any;
    InvTurnOverPrcnt: any;
    ArTurnOverPrcnt: any;
    GrowthPrcnt: any;
    WorkingCapitalAmt: any;
    OthMonthlyInstAmt: any;
    DateAsOf: any;
    Revenue: any;
    OprCost: any;
    ProfitBeforeTax: any;
    CurrAsset: any;
    NetFixedAsset: any;
    TotalAsset: any;
    CurrLiablts: any;
    LongTemrLiablts: any;
    ShareholderEquity: any;
    CurrRatio: any;
    RowVersion: string;

constructor() { 
    this.AppCustCompanyFinDataId = 0;
    this.AppCustId = 0;
    this.GrossMonthlyIncomeAmt = 0;
    this.GrossMonthlyExpenseAmt = 0;
    this.GrossProfitAmt = 0;
    this.ReturnOfInvestmentPrcnt = 0;
    this.ReturnOfEquityPrcnt = 0;
    this.ReturnOfAssetPrcnt = 0;
    this.ProfitMarginPrcnt = 0;
    this.CurrentRatioPrcnt = 0;
    this.DebtEquityRatioPrcnt = 0;
    this.InvTurnOverPrcnt = 0;
    this.ArTurnOverPrcnt = 0;
    this.GrowthPrcnt = 0;
    this.WorkingCapitalAmt = 0;
    this.OthMonthlyInstAmt = 0;
    this.Revenue = 0;
    this.OprCost = 0;
    this.ProfitBeforeTax = 0;
    this.CurrAsset = 0;
    this.NetFixedAsset = 0;
    this.TotalAsset = 0;
    this.CurrLiablts = 0;
    this.LongTemrLiablts = 0;
    this.ShareholderEquity = 0;
    this.CurrRatio = 0;
    this.RowVersion = "";
    }
}
