export class ContactInfoObj{
    name : string;
    idNo : string;
    custRelationshipName : string;
    mobilePhone : string;
    genderName : string;
    isEmergencyContact : boolean;
    mrCustRelationship : string;
    mrIdType : string;
    mrGender : string;
    motherMaidenName : string;
    idExpDt : Date;
    mrMaritalStat : string;
    birthPlace : string;
    birthDt : Date;
    mrNationality : string;
    country : string;
    email : string;
    mrEducation : string;
    profession : string;
    mrReligion : string;
    addressObj : any;   
}