// Generated by https://quicktype.io

export class CoyCommissionerObj {
    coyCommissionerId: any;
    name: any;
    jobTitle: any;
    mrIdType: any;
    idNo: any;
    taxIdNo: any;
    addr: any;
    areaCode1: any;
    areaCode2: any;
    areaCode3: any;
    areaCode4: any;
    city: any;
    zipcodeNumber: any;
    phnArea1: any;
    phn1: any;
    phnArea2: any;
    phn2: any;
    faxArea: any;
    fax: any;
    email1: any;
    mobilePhn1: any;
    mobilePhn2: any;
    refCoyId: any;
    phnArea3: any;
    phn3: any;
    email2: any;
    phnExt1: any;
    phnExt2: any;
    phnExt3: any;
    constructor() { this.coyCommissionerId = 0; }
}
