// Generated by https://quicktype.io

export class CoyCommissionerObj {
    coyCommissionerId: number;
    name: string;
    jobTitle: string;
    mrIdType: string;
    idNo: string;
    taxIdNo: string;
    addr: string;
    areaCode1: string;
    areaCode2: string;
    areaCode3: string;
    areaCode4: string;
    city: string;
    zipcodeNumber: string;
    phnArea1: string;
    phn1: string;
    phnArea2: string;
    phn2: string;
    faxArea: string;
    fax: string;
    email1: string;
    mobilePhn1: string;
    mobilePhn2: string;
    refCoyId: string;
    phnArea3: string;
    phn3: string;
    email2: string;
    phnExt1: string;
    phnExt2: string;
    phnExt3: string;
    constructor() { this.coyCommissionerId = 0; }
}
