import { AppCustAddrObj } from "./AppCustAddrObj.Model";

export class DocPickupRequestObj {
    AppNo: any;
    OfficeName: any;
    CustNo: any;
    CustName: any;
    CustId: any;
    RequestDate: any;
    RequestBy: any;
    Username: any;
    OfficeCode: any;
    OfficeId: any;
    SrvyTaskId: any;    
    SrvyOrderId: any;      
    SrvyTaskNo: any;  
    MrSurveyTypeCode: any;     
    MrSurveyTaskStatCode: any;      
    MrSrvyObjTypeCode: any;      
    RefNo: any;     
    SurveyorId: any;     
    RetrieveDt: any;     
    ResultDt: any;       
    ReviewByRefUserId: any;        
    ReviewDt: any;        
    ReviewNotes: any;    
    IsAddtReq: any;        
    PrevSurveyTaskNo: any;    
    Result: any;      
    MrCustModelCode: any;      
    CustAddr: any;       
    CustPhone: any;      
    Zipcode: any;    
    AssignDt: any;         
    SrvyFormSchmId: any;       
    Notes: any;        
    RefReasonId: any;       
    PrevSurveyorId: any;      
    MobileAssignmentId: any;        
    Kelurahan: any;       
    Kecamatan: any;      
    RT: any;       
    RW: any;       
    City: any;        
    Addr: any; 
    AppCustAddrObjs: Array<AppCustAddrObj>;
    
    
    
}