export class LeadObj{
    LeadId : string;
    TaskListId : string;
    LeadNo : string;
    LeadCopyId : string;
    OriOfficeCode : string;
    OriOfficeName : string;
    CrtOfficeCode : string;
    LeadDt : Date;
    OrderNo : string;
    LobCode : string; 
    MrLeadSourceCode : string;
    LeadStat : string;
    LeadStep : string; 
    TeleMarketingUsername : string; 
    CmoUsername : string; 
    SurveyorUsername : string;
    AgencyCode : string; 
    CancelDt : Date;
    CancelByUsername : string;
    MrCancelReasonCode : string;
    CancelNotes : string;
    DuplicateLeadId: string;
    RowVersion: string;
    IsSubmit : boolean;
    SrvyOrderNo: string;
    SubmitByUsername : string;
    SubmitDt : Date;
    CrtOfficeName : string;
    LobName : string;
    AgencyName : string;
}