export class NapAppModel {
  AppId: number;
  MouCustId: any;
  LeadId: number;
  AppNo: string;
  OriOfficeCode: string;
  OriOfficeName: string;
  CrtOfficeCode: string;
  CrtOfficeName: string;
  ProdOfferingCode: string;
  ProdOfferingName: string;
  ProdOfferingVersion: any;
  AppCreatedDt: Date;
  AppStat: string;
  AppCurrStep: string;
  AppLastStep: string;
  CurrCode: string;
  LobCode: string;
  RefProdTypeCode: string;
  Tenor: number;
  NumOfInst: number;
  PayFreqCode: string;
  MrFirstInstTypeCode: string;
  FirstInstTypeName: string;
  NumOfAsset: number;
  MrLcCalcMethodCode: string;
  LcInstRatePrml: number;
  LcInsRatePrml: number;
  MrAppSourceCode: string;
  MrWopCode: string;
  SrvyOrderNo: string;
  ApvDt: Date;
  SalesHeadNo: string;
  SalesNotes: string;
  SalesOfficerNo: string;
  CreditAdminNo: string;
  CreditAnalystNo: string;
  CreditRiskNo: string;
  DataEntryNo: string;
  MrSalesRecommendCode: string;
  MrCustNotifyOptCode: string;
  PreviousAppId: number;
  IsAppInitDone: boolean;
  MrOrderInfoCode: string;
  ApprovalStat: string;
  RsvField1: string;
  RsvField2: string;
  RsvField3: string;
  RsvField4: string;
  RsvField5: string;
  RowVersion: string;
  FloatingPeriodCode: string;
  BizTemplateCode: string;
  BlCode: string;
  ApplicationNotes: string;
  IsRos: boolean;
  CharaCredit: string;
  PrevAgrNo: string;
  WayRestructure: string;
  MrSlikSecEcoCode:string;
  constructor() {
    this.RowVersion = "";
    this.IsRos = false;
  }
}
