export class NapAppModel {
  AppId: any;
  MouCustId: any;
  LeadId: any;
  AppNo: any;
  OriOfficeCode: any;
  OriOfficeName: any;
  CrtOfficeCode: any;
  CrtOfficeName: any;
  ProdOfferingCode: any;
  ProdOfferingName: any;
  ProdOfferingVersion: any;
  AppCreatedDt: any;
  AppStat: any;
  AppCurrStep: any;
  AppLastStep: any;
  CurrCode: any;
  LobCode: any;
  RefProdTypeCode: any;
  Tenor: any;
  NumOfInst: any;
  PayFreqCode: any;
  MrFirstInstTypeCode: any;
  FirstInstTypeName: string;
  NumOfAsset: any;
  MrLcCalcMethodCode: any;
  LcInstRatePrml: any;
  LcInsRatePrml: any;
  MrAppSourceCode: any;
  MrWopCode: any;
  SrvyOrderNo: any;
  ApvDt: any;
  SalesHeadNo: any;
  SalesNotes: any;
  SalesOfficerNo: any;
  CreditAdminNo: any;
  CreditAnalystNo: any;
  CreditRiskNo: any;
  DataEntryNo: any;
  MrSalesRecommendCode: any;
  MrCustNotifyOptCode: any;
  PreviousAppId: any;
  IsAppInitDone: any;
  MrOrderInfoCode: any;
  ApprovalStat: any;
  RsvField1: any;
  RsvField2: any;
  RsvField3: any;
  RsvField4: any;
  RsvField5: any;
  RowVersion: any;
  FloatingPeriodCode: any;
  BizTemplateCode: string;
  BlCode: string;
  ApplicationNotes: string;
  IsRos: boolean;
  CharaCredit: string;
  PrevAgrNo: string;
  WayRestructure: string;
  MrSlikSecEcoCode:string;
  constructor() {
    this.RowVersion = "";
    this.IsRos = false;
  }
}
