// Generated by https://quicktype.io

export class OfficeObj {
    refOfficeId: number;
    officeCode: string;
    officeShortName: string;
    officeName: string;
    orgMdlId: number;
    officeAddr: string;
    areaCode1: string;
    areaCode2: string;
    areaCode3: string;
    areaCode4: string;
    city: string;
    zipcodeNumber: string;
    phnArea1: string;
    phn1: string;
    phnArea2: string;
    phn2: string;
    faxArea: string;
    fax: string;
    cntctPersonName: string;
    cntctPersonJobTitle: string;
    cntctPersonMobilePhn1: string;
    cntctPersonMobilePhn2: string;
    mrOfficeClass: string;
    refOfficeAreaId: number;
    isActive: boolean;
    parentId: number;
    isOfficeClose: boolean;
    officeOpeningDt: Date;
    isAllowAppCreated: boolean;
    holidaySchmHId: number;
    cntctPersonEmail1: string;
    phnArea3: string;
    phn3: string;
    cntctPersonEmail2: string;
    workingHourSchmHId: number;
    refTaxOfficeId: number;
    isVirtualOffice: boolean;
    mrKonvenSyariah: string;
    mrOfficeType:string;
    centerGrpTypeCode:string;
    centerGrpTypeName:string;

    constructor() { this.refOfficeId = 0; }
}
