// Generated by https://quicktype.io

export class RefCoyObj {
    RefCoyId: number;
    CoyCode: string;
    FullName: string;
    ShortName: string;
    InitialName: string;
    Npwp: string;
    Tdp: any;
    Siup: any;
    RegRptCode: string;
    Addr: string;
    AreaCode1: string;
    AreaCode2: string;
    AreaCode3: string;
    AreaCode4: string;
    City: string;
    Zipcode: string;
    PhnArea1: string;
    Phn1: string;
    PhnArea2: string;
    Phn2: string;
    FaxArea: string;
    Fax: string;
    CntctPersonName: string;
    CntctPersonJobTitle: string;
    CntctPersonEmail: string;
    CntctPersonEmail1: string;
    CntctPersonMobilePhn1: string;
    CntctPersonMobilePhn2: string;
    PhnExt1: string;
    PhnExt2: string;
    PhnExt3: string;
    PhnArea3: string;
    Phn3: string;
    ZipcodeNumber: string;
    TaxIdNo : string;
    RegistrationNo: string;
    LicenseNo: string;

    constructor() { this.RefCoyId = 0 }
}
