// Generated by https://quicktype.io

export class RefProvDistrictObj {
    refProvDistrictId: number;
    ProvDistrictCode: string;
    ProvDistrictName: string;
    name: string;
    districtSandiBi: string;
    parentId: number;
    type: string;
    isActive: boolean;

    constructor() { this.refProvDistrictId = 0 }
}
