// Generated by https://quicktype.io

export class RefFormObj {
    refFormId: number;
    formCode: string;
    title: string;
    path: string;
    icon: string;
    class: string;
    badgeClass: string;
    formConfiguration: string;
    parentId: number;
    orderNo: string;
    hierarchyNo: string;
    isHidden: boolean;
    isExternalLink: boolean;
    refModuleId: number;

    constructor() { this.refFormId = 0 }
}
