// Generated by https://quicktype.io

export class RefZipcodeObj {
    refZipcodeId:      number;
    areaCode2:         string;
    areaCode1:         string;
    city:              string;
    zipcodeNumber:     string;
    zipcode:           string;
    phnArea:           string;
    isActive:          boolean;
    subZipcode:        string;
    refProvDistrictId: number;
    districtName:      string;
    
  constructor() { this.refZipcodeId = 0 }
}
