// Generated by https://quicktype.io

export class RefCoyObj {
    refCoyId: number;
    coyCode: string;
    fullName: string;
    shortName: string;
    initialName: string;
    npwp: string;
    tdp: any;
    siup: any;
    regRptCode: string;
    addr: string;
    areaCode1: string;
    areaCode2: string;
    areaCode3: string;
    areaCode4: string;
    city: string;
    zipcode: string;
    phnArea1: string;
    phn1: string;
    phnArea2: string;
    phn2: string;
    faxArea: string;
    fax: string;
    cntctPersonName: string;
    cntctPersonJobTitle: string;
    cntctPersonEmail: string;
    cntctPersonEmail1: string;
    cntctPersonMobilePhn1: string;
    cntctPersonMobilePhn2: string;
    phnExt1: string;
    phnExt2: string;
    phnExt3: string;
    phnArea3: string;
    phn3: string;
    zipcodeNumber: string;
    taxIdNo : string;
    registrationNo: string;
    licenseNo: string;

    constructor() { this.refCoyId = 0 }
}
