export class RefMasterObj {
    RefMasterId: any;
    MasterCode: any;
    Descr: any;
    RefMasterTypeCode: any;
    SeqNo: any;
    ReserveField1 : any;
    ReserveField2 : any;
    ReserveField3 : any;
    ReserveField4 : any;
    ReserveField5 : any;
    IsDeletable: any;
    isSystem: any;
    IsActive: any;
    RowVersion: any;
    constructor() { this.RefMasterId = 0; this.RowVersion = '' }
}