export class AppObj {
    AppId: number;
    MouCustId: number;
    LeadId: number;
    AppNo: string;
    OriOfficeCode: string;
    OriOfficeName: string;
    CrtOfficeCode: string;
    CrtOfficeName: string;
    ProdOfferingCode: string;
    ProdOfferingName: string;
    ProdOfferingVersion: string;
    AppCreatedDt: Date;
    AppStat: string;
    AppCurrStep: string;
    AppLastStep: string;
    CurrCode: string;
    LobCode: string;
    RefProdTypeCode: string;
    Tenor: number;
    NumOfInst: number;
    PayFreqCode: string;
    MrFirstInstTypeCode: string;
    FirstInstTypeName: string;
    NumOfAsset: number;
    MrLcCalcMethodCode: string;
    LcInstRatePrml: number;
    LcInsRatePrml: number;
    MrAppSourceCode: string;
    MrWopCode: string;
    SrvyOrderNo: string;
    ApvDt: Date;
    SalesOfficerNo: string;
    SalesOfficerName: string;
    SalesNotes: string;
    SalesHeadNo: string;
    CreditAdminNo: string;
    CreditAnalystNo: string;
    CreditRiskNo: string;
    DataEntryNo: string;
    MrSalesRecommendCode: string;
    MrCustNotifyOptCode: string;
    PreviousAppId: number;
    IsAppInitDone: boolean;
    MrOrderInfoCode: string;
    ApprovalStat: string;
    RsvField1: string;
    RsvField2: string;
    RsvField3: string;
    RsvField4: string;
    RsvField5: string;
    WfTaskListId: number;
    Username: string;
    BizTemplateCode: string;
    MrCustTypeCode: string;
    RowVersion: string;
    CrdApvResultExpDt: Date;

    constructor() {
        this.AppId = 0;
        this.MouCustId = 0;
        this.LeadId = 0;
        this.AppNo = "";
        this.OriOfficeCode = "";
        this.OriOfficeName = "";
        this.CrtOfficeCode = "";
        this.CrtOfficeName = "";
        this.ProdOfferingCode = "";
        this.ProdOfferingName = "";
        this.ProdOfferingVersion = "";
        this.AppCreatedDt = new Date();
        this.AppStat = "";
        this.AppCurrStep = "";
        this.AppLastStep = "";
        this.CurrCode = "";
        this.LobCode = "";
        this.RefProdTypeCode = "";
        this.Tenor = 0;
        this.NumOfInst = 0;
        this.PayFreqCode = "";
        this.MrFirstInstTypeCode = "";
        this.NumOfAsset = 0;
        this.MrLcCalcMethodCode = "";
        this.LcInstRatePrml = 0;
        this.LcInsRatePrml = 0;
        this.MrAppSourceCode = "";
        this.MrWopCode = "";
        this.SrvyOrderNo = "";
        this.ApvDt = new Date();
        this.SalesOfficerNo = "";
        this.SalesNotes = "";
        this.SalesHeadNo = "";
        this.CreditAdminNo = "";
        this.CreditAnalystNo = "";
        this.CreditRiskNo = "";
        this.DataEntryNo = "";
        this.MrSalesRecommendCode = "";
        this.MrCustNotifyOptCode = "";
        this.PreviousAppId = 0;
        this.IsAppInitDone = false;
        this.MrOrderInfoCode = "";
        this.ApprovalStat = "";
        this.RsvField1 = "";
        this.RsvField2 = "";
        this.RsvField3 = "";
        this.RsvField4 = "";
        this.RsvField5 = "";
        this.WfTaskListId = 0;
        this.BizTemplateCode = "";
        this.MrCustTypeCode = "";
        this.RowVersion = "";
        this.CrdApvResultExpDt = new Date();
    }
}
