export class AgrmntObj {
    AgrmntId: number;
    AppId: number;
    MouCustId: number;
    LeadId: number;
    AgrmntNo: string;
    OfficeCode: string;
    OfficeName: string;
    ProdOfferingCode: string;
    ProdOfferingName: string;
    ProdOfferingVersion: string;
    CustNo: string;
    CustName: string;
    AgrmntCreatedDt: Date;
    EffectiveDt: Date;
    GoLiveDt: Date;
    AgrmntStat: string;
    AgrmntCurrStep: string;
    AgrmntLastStep: string;
    CurrCode: string;
    LobCode: string;
    RefProdTypeCode: string;
    Tenor: number;
    NumOfInst: number;
    PayFreqCode: string;
    MrFirstInstTypeCode: string;
    NumOfAsset: number;
    MrLcCalcMethodCode: string;
    LcInstRatePrml: number;
    LcInsRatePrml: number;
    MrAppSourceCode: string;
    MrWopCode: string;
    SalesOfficerNo: string;
    SalesNotes: string;
    SalesHeadNo: string;
    CreditAdminNo: string;
    CreditAnalystNo: string;
    CreditRiskNo: string;
    DataEntryNo: string;
    RsvField1: string;
    RsvField2: string;
    RsvField3: string;
    RsvField4: string;
    RsvField5: string;
    DocPrintNeedsStat: string;
    RowVersion: string;
    FirstInstTypeName: string;

    constructor() {
        this.AgrmntId = 0;
        this.AppId = 0;
        this.MouCustId = 0;
        this.LeadId = 0;
        this.AgrmntNo = "";
        this.OfficeCode = "";
        this.OfficeName = "";
        this.ProdOfferingCode = "";
        this.ProdOfferingName = "";
        this.ProdOfferingVersion = "";
        this.CustNo = "";
        this.CustName = "";
        this.AgrmntCreatedDt = new Date();
        this.EffectiveDt = new Date();
        this.GoLiveDt = new Date();
        this.AgrmntStat = "";
        this.AgrmntCurrStep = "";
        this.AgrmntLastStep = "";
        this.CurrCode = "";
        this.LobCode = "";
        this.RefProdTypeCode = "";
        this.Tenor = 0;
        this.NumOfInst = 0;
        this.PayFreqCode = "";
        this.MrFirstInstTypeCode = "";
        this.NumOfAsset = 0;
        this.MrLcCalcMethodCode = "";
        this.LcInstRatePrml = 0;
        this.LcInsRatePrml = 0;
        this.MrAppSourceCode = "";
        this.MrWopCode = "";
        this.SalesOfficerNo = "";
        this.SalesNotes = "";
        this.SalesHeadNo = "";
        this.CreditAdminNo = "";
        this.CreditAnalystNo = "";
        this.CreditRiskNo = "";
        this.DataEntryNo = "";
        this.RsvField1 = "";
        this.RsvField2 = "";
        this.RsvField3 = "";
        this.RsvField4 = "";
        this.RsvField5 = "";
        this.DocPrintNeedsStat = "";
        this.RowVersion = "";
        this.FirstInstTypeName = "";
    }
}
